const wyzwania = [
    "Zrób 10 pompek",
    "Idź na 30 minutowy spacer",
    "Podnieś 20 kilo na sztandze",
    "Przeczytaj 20 stron książki",
    "Wypij 2 litry wody",
    "Zrób porządek na biurku",
    "Spędź godzinę bez telefonu",
    "Zjedz ślimaka",
    "Przebiegnij 2 km",
    "Zrób 30 przysiadów",
    "Posłuchaj polityków muzyki",
    "Zrób Obraz",
    "Pomóż bezdomnemu",
    "Rób deskę przez minutę",
    "Wyjdź na zakupy za kogoś",
    "Zorganizuj swoje pliki",
    "Zrób porządek u kogoś",
    "Uśmiechnij się do 5 osób",
    "Zaplanuj jutrzejszy dzień",
    "Podziękuj za ten dzień"
];